name: Build Project

on:
  workflow_dispatch:
  release:
    types: [published]
  #push:
    #branches: [ "main" ]
  
jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: windows-2025

    strategy:
      fail-fast: false # Don't cancel other jobs in the matrix if one job fails
      matrix:
        include:
          - name: Release_Itch_x86
            platform: x86
            configuration: Release
            path: Release

          - name: Release_x64
            platform: x64
            configuration: Release
            path: x64\Release

          - name: Debug_Itch_x86
            platform: x86
            configuration: Debug
            path: Debug

          - name: Debug_x64
            platform: x64
            configuration: Debug
            path: x64\Debug

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3

      - name: Build SickoMenu.dll
        shell: bash
        run: MSBuild.exe -property:Configuration=${{ matrix.configuration }} -property:PlatformToolset=v143 -property:Platform=${{ matrix.platform }}

      - name: Build version.dll
        shell: bash
        run: MSBuild.exe -property:Configuration=${{ matrix.configuration }}_Version -property:PlatformToolset=v143 -property:Platform=${{ matrix.platform }}

      - name: Package
        shell: cmd
        run: |
          move /y "${{ matrix.path }}\SickoMenu.dll" SickoMenu.dll
          move /y "${{ matrix.path }}_Version\version.dll" version.dll
          tar -caf "${{ matrix.name }}.zip" SickoMenu.dll version.dll LICENSE

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}.zip

  AutoRelease:
    runs-on: windows-2025
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
      
      - name: Automatic Releases
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          prerelease: false
          generate_release_notes: true
          files: |
            Release_x86_SteamItch/Release_Itch_x86.zip
            Release_x64_EpicXboxMS/Release_x64.zip
            Debug_x86_SteamItch/Debug_Itch_x86.zip
            Debug_x64_EpicXboxMS/Debug_x64.zip
